### ISSUE TITLE
[FR] Combine Thumbnails

### ISSUE THREAD

**Issue by thexmanxyz** [joomlaworks/simple-image-gallery#13]
Hey there, as a first hello to the repository I want to propose a feature request which might also be very useful to others and revalue the whole plugin. I would be great to have an option to enable that all thumbnails of an gallery are merged into one single image when converted. The single thumbnails are then stripped out from the image via CSS when rendered.

This would reduce the transfer overhead by a huge amount because it would be no longer necessary to fetch many tiny image files but rather one big one. This would render an image gallery a lot faster. I'm not sure if this is supported by fancyBox but I guess there is a way to achieve this.

I really like this plugin and I would love to see this coming as an option. I would also offer my help. I will now also add some PRs to this repo with changes I made for myself to bring the project a bit forward.

**Comment by fevangelou** [comment]
This is actually a misconception. In the age of HTTP/2 it's far more efficient to use smaller files than large chunks. Plus, because you merge images together, doesn't mean the actual size decreases a lot.

In the future, please consider these to write-ups about open source:
http://people.redhat.com/~rjones/how-to-supply-code-to-open-source-projects/
https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9

**Comment by thexmanxyz** [comment]
@fevangelou Thanks for pointing on this two interesting pages. But the behaviour described there has by no means anything in common with the actions / contributions I made to your repo today. If you feel I did things like that, I would suggest to read the stuff written there attentively by yourself. Even though I wish you a nice day. Don't be so damn arrogant...

**Comment by fevangelou** [comment]
It's not arrogance. It's being practical. I've run SIG since 2006. I know a thing or two on communities, contributing etc. I've done K2 which has a gazillion options. Don't you think I understand what should go into something or not after all this time (and millions of downloads)?

Had you read the 2nd link I sent you (which is from the creators of a popular open source project) you'd clearly NOT miss the first 4 paragraphs:

> The only people entitled to say how open source 'ought' to work are people who run projects, and the scope of their entitlement extends only to their own projects.

> Just because someone open sources something does not imply they owe the world a change in their status, focus and effort, e.g. from inventor to community manager.

> As a user of something open source you are not thereby entitled to anything at all. You are not entitled to contribute. You are not entitled to features. You are not entitled to the attention of others. You are not entitled to having value attached to your complaints. You are not entitled to this explanation.

> If you have expectations (of others) that aren't being met, those expectations are your own responsibility. You are responsible for your own needs. If you want things, make them.

I get it, you want to make SIG better. But "better" is objective. It may be better for you. It doesn't necessarily mean it's better for others, just because it has extra options. There's a reason I stressed the "simple" word.

**Comment by thexmanxyz** [comment]
@fevangelou Your behaviour and the way you handled the contributions is arrogant, period. If you see that differently, fine. You might know a lot about communities, contributions, etc. as well as you probably know and understand what should go into something or not. Granted.

TBH I read that and I do not get your point, if the mistake was, that I did the contribution at all then I'm sorry. I will take care on that in the future when I stumble over one of your repositories and don't touch anything to prevent to get you in a bad mood.

I did not even discuss on the PRs or demanded a merge. I just proposed my changes and that's it. If you allow input (which is part of GitHubs design) then you also have to handle it properly and don't act this way.

But I have also a good hint for the future for you. But it's only from me, reject the PRs that are out of scope and that's it. Instead of blaming people for doing something wrong that only try to contribute.
